### ISSUE TITLE
Javatools do not work with M2crypto 0.25.0

### ISSUE THREAD

**Issue by KonstantinShemyak** [KonstantinShemyak/python-javatools#14]
The last working version is M2crypto 0.24.0. Since 0.25.0, unit tests (and everything else, too) related to crypto operations fail:

```$ python setup.py test
running test
running egg_info
writing requirements to javatools.egg-info/requires.txt
writing javatools.egg-info/PKG-INFO
writing top-level names to javatools.egg-info/top_level.txt
writing dependency_links to javatools.egg-info/dependency_links.txt
reading manifest file 'javatools.egg-info/SOURCES.txt'
writing manifest file 'javatools.egg-info/SOURCES.txt'
running build_ext
Traceback (most recent call last):
  File "setup.py", line 81, in <module>
    'pylint': pylint_cmd } )
  File "/usr/lib/python2.7/distutils/core.py", line 151, in setup
    dist.run_commands()
  File "/usr/lib/python2.7/distutils/dist.py", line 953, in run_commands
    self.run_command(cmd)
  File "/usr/lib/python2.7/distutils/dist.py", line 972, in run_command
    cmd_obj.run()
  File "/home/konstantin/src/p-j-venv/local/lib/python2.7/site-packages/setuptools/command/test.py", line 159, in run
    self.with_project_on_sys_path(self.run_tests)
  File "/home/konstantin/src/p-j-venv/local/lib/python2.7/site-packages/setuptools/command/test.py", line 140, in with_project_on_sys_path
    func()
  File "/home/konstantin/src/p-j-venv/local/lib/python2.7/site-packages/setuptools/command/test.py", line 180, in run_tests
    testRunner=self._resolve_as_ep(self.test_runner),
  File "/usr/lib/python2.7/unittest/main.py", line 94, in __init__
    self.parseArgs(argv)
  File "/usr/lib/python2.7/unittest/main.py", line 149, in parseArgs
    self.createTests()
  File "/usr/lib/python2.7/unittest/main.py", line 158, in createTests
    self.module)
  File "/usr/lib/python2.7/unittest/loader.py", line 130, in loadTestsFromNames
    suites = [self.loadTestsFromName(name, module) for name in names]
  File "/usr/lib/python2.7/unittest/loader.py", line 103, in loadTestsFromName
    return self.loadTestsFromModule(obj)
  File "/home/konstantin/src/p-j-venv/local/lib/python2.7/site-packages/setuptools/command/test.py", line 38, in loadTestsFromModule
    tests.append(self.loadTestsFromName(submodule))
  File "/usr/lib/python2.7/unittest/loader.py", line 100, in loadTestsFromName
    parent, obj = obj, getattr(obj, part)
AttributeError: 'module' object has no attribute 'crypto'
```

The reason for this is that `javatools.crypto` fails to import:

```$ python
Python 2.7.12 (default, Jul  1 2016, 15:12:24) 
[GCC 5.4.0 20160609] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> from javatools import crypto
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "javatools/crypto.py", line 23, in <module>
    from M2Crypto import SMIME, X509, BIO, RSA, DSA, EC, m2
  File "/home/konstantin/src/p-j-venv/local/lib/python2.7/site-packages/M2Crypto/__init__.py", line 26, in <module>
    from M2Crypto import (ASN1, AuthCookie, BIO, BN, DH, DSA, EVP, Engine, Err,
  File "/home/konstantin/src/p-j-venv/local/lib/python2.7/site-packages/M2Crypto/ASN1.py", line 15, in <module>
    from M2Crypto import BIO, m2, util
  File "/home/konstantin/src/p-j-venv/local/lib/python2.7/site-packages/M2Crypto/BIO.py", line 10, in <module>
    from M2Crypto import m2, util
  File "/home/konstantin/src/p-j-venv/local/lib/python2.7/site-packages/M2Crypto/m2.py", line 30, in <module>
    from M2Crypto._m2crypto import *
  File "/home/konstantin/src/p-j-venv/local/lib/python2.7/site-packages/M2Crypto/_m2crypto.py", line 26, in <module>
    __m2crypto = swig_import_helper()
  File "/home/konstantin/src/p-j-venv/local/lib/python2.7/site-packages/M2Crypto/_m2crypto.py", line 22, in swig_import_helper
    _mod = imp.load_module('__m2crypto', fp, pathname, description)
ImportError: /home/konstantin/src/p-j-venv/local/lib/python2.7/site-packages/M2Crypto/__m2crypto.so: undefined symbol: SSLv2_method
>>> 
```

**Comment by KonstantinShemyak** [comment]
Filed https://gitlab.com/m2crypto/m2crypto/issues/150

**Comment by KonstantinShemyak** [comment]
Does not reproduce.
