### ISSUE TITLE
Dependency on M2Crypto is not correctly handled

### ISSUE THREAD

**Issue by KonstantinShemyak** [KonstantinShemyak/python-javatools#18]
In a fresh environment:
```
$ python setup.py test
running test
Searching for M2Crypto
Best match: M2Crypto 0.25.1
Processing M2Crypto-0.25.1-py2.7-linux-x86_64.egg

Using /home/konstantin/src/python-javatools/.eggs/M2Crypto-0.25.1-py2.7-linux-x86_64.egg
Searching for typing
Best match: typing 3.5.2.2
Processing typing-3.5.2.2-py2.7.egg

Using /home/konstantin/src/python-javatools/.eggs/typing-3.5.2.2-py2.7.egg
running egg_info
writing requirements to javatools.egg-info/requires.txt
writing javatools.egg-info/PKG-INFO
writing top-level names to javatools.egg-info/top_level.txt
writing dependency_links to javatools.egg-info/dependency_links.txt
reading manifest file 'javatools.egg-info/SOURCES.txt'
writing manifest file 'javatools.egg-info/SOURCES.txt'
running build_ext
Traceback (most recent call last):
  File "setup.py", line 81, in <module>
    'pylint': pylint_cmd } )
  File "/usr/lib/python2.7/distutils/core.py", line 151, in setup
    dist.run_commands()
  File "/usr/lib/python2.7/distutils/dist.py", line 953, in run_commands
    self.run_command(cmd)
  File "/usr/lib/python2.7/distutils/dist.py", line 972, in run_command
    cmd_obj.run()
  File "/home/konstantin/src/python-javatools/p-j-venv/local/lib/python2.7/site-packages/setuptools/command/test.py
", line 211, in run
    self.run_tests()
  File "/home/konstantin/src/python-javatools/p-j-venv/local/lib/python2.7/site-packages/setuptools/command/test.py
", line 234, in run_tests
    **exit_kwarg
  File "/usr/lib/python2.7/unittest/main.py", line 94, in __init__
    self.parseArgs(argv)
  File "/usr/lib/python2.7/unittest/main.py", line 149, in parseArgs
    self.createTests()
  File "/usr/lib/python2.7/unittest/main.py", line 158, in createTests
    self.module)
  File "/usr/lib/python2.7/unittest/loader.py", line 130, in loadTestsFromNames
    suites = [self.loadTestsFromName(name, module) for name in names]
  File "/usr/lib/python2.7/unittest/loader.py", line 103, in loadTestsFromName
    return self.loadTestsFromModule(obj)
  File "/home/konstantin/src/python-javatools/p-j-venv/local/lib/python2.7/site-packages/setuptools/command/test.py
", line 43, in loadTestsFromModule
    tests.append(self.loadTestsFromName(submodule))
  File "/usr/lib/python2.7/unittest/loader.py", line 100, in loadTestsFromName
    parent, obj = obj, getattr(obj, part)
AttributeError: 'module' object has no attribute 'crypto'
```

Workaround: install `m2crypto`.

**Comment by KonstantinShemyak** [comment]
Unfortunately I cannot reproduce this now.
```
virtualenv p-j-venv
source p-j-venv/bin/activate
pip install Cheetah
python setup.py test
```
Works fine.
